### ISSUE TITLE
Add more info about shapes

### ISSUE THREAD

**Issue by ClaudiuC** [hhvm/hack-hhvm-docs#132]
We should probably mention that shapes need literal strings for keys and detail the benefits of shapes as opposed to a class with public methods. Some info about setting keys to nullable types and how that works would be nice too. 

http://docs.hhvm.com/manual/en/hack.shapes.acrossfiles.php also needs some work IMO (can you really define a key as null?), maybe just defining return types everywhere to make it clear you're passing `RandomData` around?

**Comment by JoelMarcey** [comment]
Thanks @ClaudiuC  :)

Fix in the new docs: https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
