### ISSUE TITLE
Bug in HHVM and Hack Manual

### ISSUE THREAD

**Issue by raymondjplante** [hhvm/hack-hhvm-docs#156]
I can't find any reference for the newer ini style config settings like:
* hhvm.server.file_socket

Is there a page with the settings on them and what values they take?

**Comment by JoelMarcey** [comment]
This will be more clearly explained in the new docs we are developing. See https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo

But you can go here for now... https://github.com/facebook/hhvm/wiki/INI-Settings
