### ISSUE TITLE
Bug in T<mixed> Compatibility

### ISSUE THREAD

**Issue by ThatRfernand** [hhvm/hack-hhvm-docs#170]
Consider adding a definition and discussion on the "mixed" type (or a link to it, if it exists.)

This entry starts by pointing out that "mixed" is a source of confusion, and it's not entirely obvious to a newcomer why this type exists when "T"-style generics are around.

**Comment by JoelMarcey** [comment]
Yep. We will have in new docs.

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
