### ISSUE TITLE
Super globals in strict mode

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hack-hhvm-docs#184]
Could be useful to provide some examples of using `[filter_input](http://php.net/filter_input)` to access the super globals in strict mode.

**Comment by JoelMarcey** [comment]
@jwatzman Is this something we want to call out in the new docs? Is this a recommended pattern?

**Comment by jwatzman** [comment]
We've always had partial-mode wrappers (http://cookbook.hacklang.org/recipes/get-and-post/) but I don't feel particularly strongly about this. Ideally strict mode would have a better option anyways, but not sure when we'll get to that.
