### ISSUE TITLE
Bug in Unsupported PHP Features in Hack

### ISSUE THREAD

**Issue by TJ09** [hhvm/hack-hhvm-docs#190]
The Hack typechecker does not support "aliasing" of methods defined in traits

e.g.:
```
  class Hello {
    use MyTrait {
        someFunction as someAlias;
    }
  }
```

Since it appears to be an intentional choice not to support this behavior (which is fine), I believe it should be documented on the "Unsupported PHP Features" page.

**Comment by JoelMarcey** [comment]
I have added a placeholder for this in the new docs.
