### ISSUE TITLE
Bug in Shapes

### ISSUE THREAD

**Issue by meitros** [hhvm/hack-hhvm-docs#198]
Of all the hack docs, this one has always been the most confusing and least helpful to me. A few suggestions:

1. Make the motivating example better (based on a real example)
2. Show the actual syntax for using shapes..maybe by rewriting the motivating example into the new syntax. Right now, we don't even show how to create an instance of a shape.
3. Clarify why you might want to use type versus newtype with shapes (based on real examples from the codebase)

**Comment by JoelMarcey** [comment]
We will make shapes better in the new documentation. https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
