### ISSUE TITLE
Docs don't mention that Phar is currently read only

### ISSUE THREAD

**Issue by aewing** [hhvm/hack-hhvm-docs#212]
There is currently no write support for Phar and the [documentation](http://docs.hhvm.com/manual/en/intro.phar.php) doesn't appear to note this.

**Comment by JoelMarcey** [comment]
This is a php.net thing. In the new docs, we will defer to php.net in things we support similarly.

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
