### ISSUE TITLE
Document HHVM/Hack specific APIs.

### ISSUE THREAD

**Issue by Aatch** [hhvm/hack-hhvm-docs#221]
This is mostly for my own benefit tracking the progress of this.

There are a number of functions and classes that are implemented in HHVM that are quite useful. These should be documented where appropriate. An initial survey suggests the following components:

* [ ] Pagelet Server
* [ ] X-Box Server
* [ ] Performance Counters and Statistics
* [ ] Xenon
* [ ] HHVM Debugger
* [ ] Thrift
* [ ] Miscellanous HHVM/Hack Functions

And the following additions to existing extensions (based on their current location):

* [ ] **Array**
  * `hphp_array_idx`
* [ ] **Options**
  * `clock_getres`
  * `clock_gettime`
  * `clock_settime`
  * `cpu_get_count`
  * `cpu_get_model`
* [ ] **Zlib**
  * `lz4compress`
  * `lz4uncompress`
  * `lz4hccompress`
  * `qlzcompress`
  * `qlzuncompress`
  * `nzcompress`
  * `nzuncompress`
* [ ] **Function Handling**
  * `register_postsend_callback`
* [ ] **XHProf**
  * `xhprof_frame_begin`
  * `xhprof_frame_end`
  * `xhprof_network_enable`
  * `xhprof_network_disable`

There are a few other functions that aren't mentioned here as I am unsure of whether they should be considered external or internal functions.

**Comment by JoelMarcey** [comment]
A lot of these exist on our new doc API reference. Let us know if you need more by filing an issue at our new repo..

https://github.com/hhvm/user-documentation
