### ISSUE TITLE
Bug in Unsupported PHP Features in Hack

### ISSUE THREAD

**Issue by Libbux** [hhvm/hack-hhvm-docs#292]
The fact that superglobals are unsupported should be added as a footnote to the fact that globals aren't supported, as this is a major incompatibility point for a lot of ~~poorly written~~ code. This is related to issue #184.

**Comment by JoelMarcey** [comment]
We will see what is said in #184  

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
