### ISSUE TITLE
Bug in HHVM and Hack Manual

### ISSUE THREAD

**Issue by hashar** [hhvm/hack-hhvm-docs#302]
The documentation on hvvm.com could use an overview of what the VM system is.  I eventually found a public post on facebook.com which might be worth integrating in the online documentation:

https://www.facebook.com/notes/facebook-engineering/the-hiphop-virtual-machine/10150415177928920

Been written by Jason Evans back in December 2011.  I am assuming it has been written on behalf of Facebook and thus copyright belong to Facebook, so it should be easy (read: legal) to copy paste the post to the doc :]

**Comment by JoelMarcey** [comment]
Will have more documentation about this in the new docs ... https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
