### ISSUE TITLE
hhvm.com can not access from china

### ISSUE THREAD

**Issue by reeze** [hhvm/hack-hhvm-docs#303]
I don't know where can I submit the issue.   maybe it is the  same reason we can't access facebook.com from China, we can do nothing to make facebook.com accessible, but I hope hhvm.com could be accessible (a least we could use package manager to install hhvm from source), it will be useful for HHVM promotion in China.  There are a lot of company start to use hhvm. 

If I could do anything to help resolve the issue, drop me a line :)

**Comment by JoelMarcey** [comment]
I am going to close this @reeze. It is old, you can open up a new issue if it is still a problem.
