### ISSUE TITLE
Bug in LibXML Runtime Configuration Documentation

### ISSUE THREAD

**Issue by jvanharn** [hhvm/hack-hhvm-docs#374]
http://docs.hhvm.com/manual/en/libxml.configuration.php
The latest HHVM update requires "hhvm.libxml.ext_entity_whitelist" to be set for libxml file inclusion in xslt. This breaks compatibility with many frameworks using xslt for templating and I imagine people wondering why that is, luckily this is documented in the error message itself, however, explaining formatting and what it's values actually mean seems necessary. Detailing which protocols can be added here and/or qualifiers for the protocols to be added and in what format would be helpful.

This is the only currently existing documentation of this "feature":
https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies#L133

**Comment by JoelMarcey** [comment]
I have a placeholder for inconsistencies in our new docs... https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
