### ISSUE TITLE
Documentaton to compile extensions against official Debian/Ubuntu packages

### ISSUE THREAD

**Issue by btegs** [hhvm/hack-hhvm-docs#378]
The HHVM documentation recommends the usage of mongofill-hhvm at https://github.com/mongofill/mongofill-hhvm to use MongoDB under HHVM.

When looking at the documentation on both the HHVM and mongofill-hhvm pages, it talks about compiling from source against a manually compiled HHVM package and not the official Debian and Ubuntu packages offered in the repositories located at http://dl.hhvm.com/ubuntu.

It would be nice to have a guide so extensions can be compiled against the hhvm and hhvm-dev packages offered in your repos. Thanks!

**Comment by JoelMarcey** [comment]
I have a placeholder for this in the new docs https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
