### ISSUE TITLE
Document the IMemoizeParam interface

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/hack-hhvm-docs#382]

**Comment by steelbrain** [comment]
Bump

**Comment by JoelMarcey** [comment]
I have this as a placeholder in the new docs... 

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo

**Comment by JoelMarcey** [comment]
See if this helps you; it will be in the new docs upcoming: https://github.com/hhvm/user-documentation/blob/master/guides/hack/11-attributes/04-special.md#__memoize

**Comment by steelbrain** [comment]
@JoelMarcey Nice! Thanks!
