### ISSUE TITLE
Bug in MutableSet<Tv>

### ISSUE THREAD

**Issue by jaderfeijo** [hhvm/hack-hhvm-docs#404]
Could not find documentation for the `MutableCollection<Tv>` and `MutableSetAccess<Tv>` interfaces. Although I believe these are included in the documentation for `MutableSet<Tv>` and their methods can be inferred from there I think it would be good for them to have their own documentation pages, even if they aren't meant to be used directly, it would be good for that to be mentioned in their own documentation pages like it is for [KeyedTraversible](http://docs.hhvm.com/manual/en/class.hack.keyedtraversabletktv.php).

**Comment by JoelMarcey** [comment]
https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
