### ISSUE TITLE
Bug in The configuration file

### ISSUE THREAD

**Issue by buggy82** [hhvm/hack-hhvm-docs#416]
http://docs.hhvm.com/manual/en/configuration.file.php

"Not all HHVM directives are necessarily documented in this manual: for a complete list of directives available in your HHVM version, please read your well commented php.ini file."

My /etc/hhvm/php.ini file does not have any comments explaining available hhvm directives:

; php options
date.timezone=Europe/Berlin
; hhvm specific
hhvm.server.type = fastcgi
hhvm.server.port = 9000
hhvm.server.source_root = /var/www
hhvm.server.default_document = index.php
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.mysql.typed_results = false

**Comment by JoelMarcey** [comment]
These will be documented in our new docs https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
