### ISSUE TITLE
Bug in Heredocs

### ISSUE THREAD

**Issue by bryanboyan** [hhvm/hack-hhvm-docs#418]
I did my own test as below 
```php
<?hh

function heredoc(): string {
  $y = 13;
  $x = <<<MYHD
Hello, I am in here\n
{$y}
MYHD;
  return $x;
}

echo heredoc()."\n";
```
And I got output like this:
```sh
Hello, I am in here

13
```

Don't know if there's some version problem here.

**Comment by JoelMarcey** [comment]
You are right, that limitation is gone now. I will not mention this in our new docs...

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
