### ISSUE TITLE
Add possiblity to whitelist functions from being "not supported"

### ISSUE THREAD

**Issue by SiebelsTim** [hhvm/hack-hhvm-docs#441]
Currently at least `odbc_*` suffers from this. As well as all externally provided extension.

**Comment by SiebelsTim** [comment]
@JoelMarcey What did we agree on? Installing third-party & enabling zend compat on the docs machine, or adding a whitelist?

**Comment by JoelMarcey** [comment]
Our new API reference infra should hopefully take care of all this.
