### ISSUE TITLE
FAQ / Single Document for the Hack convenience syntax

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/hack-hhvm-docs#447]
People have been asking for a cheatsheet for Hack, particularly around the different "convenience" syntax that is available:

```
?->
@
->:xhp-attr
+/- for co/contravariance
:
:
```

cc: @jwatzman

**Comment by jwatzman** [comment]
I think this should be rolled into the FAQ at #455 right?

**Comment by JoelMarcey** [comment]
@jwatzman Yep. I think the #455 FAQ will close out some other issues here too.
