### ISSUE TITLE
Bug in Examples

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/hack-hhvm-docs#453]
One useful thing not mentioned anywhere on the pages for lambda expressions is how to specify a return type. The following shows this:

	$fn = ($a): int ==> $a * 2;

As with other, non-trivial cases, the parens around the parameter list are required.

**Comment by SiebelsTim** [comment]
It's listed last, isn't it?

    Use parentheses if you need to provide parameter or return type hints, or if you need to provide default values for parameters: 

http://docs.hhvm.com/manual/en/hack.lambda.examples.php

**Comment by RexJaeschke** [comment]
Yes, I guess it is, but being the very last thing, way back in an example page, it wasn’t at all obvious when reading the text.

 

Rex

**Comment by SiebelsTim** [comment]
So I suggest to add mention it somewhere in the text.
