### ISSUE TITLE
Bug in hack.maptktv.construct.php

### ISSUE THREAD

**Issue by edormanfacebook** [hhvm/hack-hhvm-docs#469]
Small bug in this page: It says that in order to construct a new map it should be:
$v = new Map();

but really it should be:

$v = Map { };

Fixing this doc might help clear up confusion for beginners like me :)

**Comment by SiebelsTim** [comment]
I don't see an example where it says to use `new Map()`. There is one example that creates a map from array. We can't do that with the literal syntax though. 
Am I missing something?

**Comment by edormanfacebook** [comment]
In http://docs.hhvm.com/manual/en/hack.maptktv.construct.php, search for "new Map()". That is what I was referring to.

**Comment by SiebelsTim** [comment]
Oh yeah, I agree. Empty Maps should be created with the literal syntax.
