### ISSUE TITLE
Bug in function.phpinfo.php

### ISSUE THREAD

**Issue by winks** [hhvm/hack-hhvm-docs#470]
This seems to be 95% equal to http://php.net/phpinfo and, what's worse, it ranks quite highly for searches for "hhvm phpinfo" - but it only yields "HipHop" (ref: https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/std/ext_std_options.cpp#L912 )

So while "Not yet implemented" is technically wrong, the docs should be amended to state "it just returns 'HipHop' and the INFO_* constants are ignored"

**Comment by xxorax** [comment]
Please be more specific in the doc: phpinfo function doesn't return any usefull information in php too, it returns boolean. So the warning can be interpreted differently.

Maybe just change the warning to "This function does not **display** any useful information yet." but I thnk it's better to just remove the php doc here.

**Comment by SiebelsTim** [comment]
Exposed information has improved just recently :)
https://github.com/facebook/hhvm/commit/57b7c37cfbc00948860e43b035220f377cd24e06

**Comment by JoelMarcey** [comment]
@fredemmott This is a good test function for our new API docs, probably. Make sure our documentation for this function comes from us instead of php.net

**Comment by JoelMarcey** [comment]
https://github.com/hhvm/user-documentation/issues/161
