### ISSUE TITLE
Bug in function.uasort.php

### ISSUE THREAD

**Issue by naydav** [hhvm/hack-hhvm-docs#473]
I have problem with HHVM

```php
<?php
$testSort = array('key1' => 'key1', 'key2' => 'key2');

uasort($testSort, function ($a, $b) {
    return 0; // like as elements are equal
});
print_r($testSort);
```

PHP:
```
Array
(
    [key1] => key1
    [key2] => key2
)
```

HHVM
```
Array
(
    [key2] => key2
    [key1] => key1
)
```

http://3v4l.org/mQOBV#v530

**Comment by SiebelsTim** [comment]
This was already discussed here https://github.com/facebook/hhvm/issues/4649

**Comment by paulbiss** [comment]
>Note:
>If two members compare as equal, their relative order in the sorted array is undefined.

http://php.net/manual/en/function.uasort.php
