### ISSUE TITLE
Bug in hack.async.awaitablesvscontinuations.php

### ISSUE THREAD

**Issue by cgthayer** [hhvm/hack-hhvm-docs#478]
Would benefit from a discussion of exceptions here somewhere.

**Comment by JoelMarcey** [comment]
Our new docs has a better async section, with a section on exceptions. They are raw right now, but you can see what we are up to...

https://github.com/hhvm/user-documentation/blob/master/hack/async/exceptions.md

The examples are being auto-inserted via @@, so you can just browse to the appropriate directory to see the example files.
