### ISSUE TITLE
Split example code to separate files, include into documentation, test automatically

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hack-hhvm-docs#482]
Should have:
- snippet.php
- snippet.php.hh_expect
- snippet.php.runtime_expect

or similar

**Comment by SiebelsTim** [comment]
Oooh yes! I agree on hi-pri,  Joel :)

**Comment by JoelMarcey** [comment]
@SiebelsTim I am doing a test now. And depending on how it is looking, the hi pri task might come back vs wishlist :)

**Comment by fredemmott** [comment]
Didn't this get done?

**Comment by SiebelsTim** [comment]
Automatic testing is yet to be done.
