### ISSUE TITLE
Bug in hack.xhp.returningxhpelements.php

### ISSUE THREAD

**Issue by Swahvay** [hhvm/hack-hhvm-docs#486]
Your example code has `<:div>` instead of `<div>` on line 6.

**Comment by Swahvay** [comment]
This same mistake is also in `hack.xhp.future.php`.

**Comment by JoelMarcey** [comment]
We are updating our XHP documentation in the new docs....

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
