### ISSUE TITLE
Typo in hack.attributes.php

### ISSUE THREAD

**Issue by kentaromiura** [hhvm/hack-hhvm-docs#491]
there's a typo: attrubute instead of attribute:
https://github.com/hhvm/hack-hhvm-docs/blob/master/__docs/phpdoc/en/hack/attributes.xml#L19

**Comment by SiebelsTim** [comment]
Fixed in https://github.com/hhvm/hack-hhvm-docs/commit/72e47aaa398c3603b26263616c029b7cc77266f1
