### ISSUE TITLE
Bug in Examples

### ISSUE THREAD

**Issue by Warbo** [hhvm/hack-hhvm-docs#50]
The lambda examples show an implicit return value, like this:

$foo = $x ==> $x + 1;

They also show compound statements, like this:

$dump_map = ($name, $x) ==> {
  echo "Map $name has:\n";
  foreach ($x as $k => $v) {
    echo "  $k => $v\n";
  }
};

There is no mention of whether compound statements have an implicit return value (like Scheme and ML, for example) or not. I imagine they don't, ie. it is mandatory to use the "return" keyword, but that's a guess.

**Comment by JoelMarcey** [comment]
Better examples in the new docs. See: https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
