### ISSUE TITLE
Document how to wrap async mysql's queryf() function, preserving typechecker support for the patterns

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hack-hhvm-docs#505]
```Hack
<?hh

newtype FormatString<T> = string;
function my_queryf(FormatString<HH\SQLFormatter> $foo, ...$args) {
  $conn = new AsyncMysqlConnection(); // Actually use AsyncMysqlClient::connect
  /* HH_FIXME[4110]
   *
   * This should be HH\FormatString, not FormatString - however,
   * if we define the type for HH\FormatString, it's a duplicate against the
   * hhi, and if we don't, it's undefined at runtime due to facebook/hhvm#4831.
   */
  $conn->queryf($foo, ...$args);
}
```

**Comment by fredemmott** [comment]
cc @jwatzman to check for correctness

**Comment by jwatzman** [comment]
Ick, I hate to codify the fixme for this. But this is a key part of the async mysql functionality, right, and the fix for newtype in systemlib is complicated?

**Comment by fredemmott** [comment]
- newtype fix is complicated (facebook/hhvm#4831)
- for safety, it's a really good idea to wrap these so that fetching the connection and executing the query are one action. I feel that makes this key.

**Comment by fredemmott** [comment]
Also, even when the FIXME isn't required, typechecked varargs still needs documenting :)

**Comment by JoelMarcey** [comment]
I am going to document typechecked varargs ... do we still need this specifically?

**Comment by fredemmott** [comment]
uneeded in 3.9
