### ISSUE TITLE
Bug in hack.xhp.returningxhpelements.php

### ISSUE THREAD

**Issue by TJ09** [hhvm/hack-hhvm-docs#513]
On: http://docs.hhvm.com/manual/en/hack.xhp.returningxhpelements.php 

The final bullet point references "render_in_a_box() in the example above," but the sample "render_in_a_box()" function is not mentioned above. It is instead shown on a different page (http://docs.hhvm.com/manual/en/hack.xhp.xhpchild.php)

**Comment by JoelMarcey** [comment]
We will have better examples in our new docs...

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
