### ISSUE TITLE
Bug in install.xhp.php - should say to use '2.x-dev' , definitely not dev-master.

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hack-hhvm-docs#515]
See http://facebook.github.io/xhp-lib/2015/03/04/composer-branches-2.0.html

Alternatively, just tell people to look at https://packagist.org/packages/facebook/xhp-lib for available versions

**Comment by JoelMarcey** [comment]
Unless you think this particular bug is high pri enough that I make the change to the current docs.

If so, let me know and we can make the change and generate again.
