### ISSUE TITLE
Bug in hack.shapes.php: Doesn't describe how to construct a shape

### ISSUE THREAD

**Issue by admdikramr** [hhvm/hack-hhvm-docs#519]
newtype MyShape = shape('id1' => <:type>, 'id2' => <:type>);

leads me to expect that I should be able to construct one using "new MyShape($thing1, $thing2)", but in fact I have to use shape('id1' => $thing1, 'id2' => $thing2).

This is counterintuitive, but fine -- it just needs to be documented.

**Comment by JoelMarcey** [comment]
We will have new Shapes documentation in our new docs...

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
