### ISSUE TITLE
HH\asio\curl_exec in strict mode

### ISSUE THREAD

**Issue by tchapi** [hhvm/hack-hhvm-docs#533]
Hi,

I didn't find any mention in the docs that the typechecker would choke on `HH\asio\curl_exec` when in *strict* mode: 

    Unbound name: HH\asio\curl_exec (a global constant) (Naming[2049])
    Unbound name: HH\asio\curl_exec (a global function) (Naming[2049])
    Unbound name (typing): HH\asio\curl_exec (Typing[4107])

Is this normal and should we add `// UNSAFE` for instance ? That would be worth mentionning I guess

Thanks !

**Comment by paulbiss** [comment]
Looks like it's already been [added](https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/stdlib/builtins_curl.hhi#L263-L265) to the runtime, try capitalizing Asio.

**Comment by tchapi** [comment]
I tried both (caps and lowercase), and same result. Might not be released yet ? I've got the latest release I guess : 

    vagrant@precise64:/vagrant$ hhvm --version
    HipHop VM 3.6.1 (rel)
    Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
    Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3

**Comment by paulbiss** [comment]
Looks like the commit is just in master (aa16c07ba217b71a1aa6f64393e4d7aab0e02129), we're going to cherry-pick it for 3.6.2

**Comment by tchapi** [comment]
Great ! Thanks a lot for the heads-up

**Comment by fredemmott** [comment]
This should be resolved; if not, please open an issue against HHVM itself

**Comment by tchapi** [comment]
Resolved, thanks a lot !
