### ISSUE TITLE
$stClassObject->{$var} notation in strict mode

### ISSUE THREAD

**Issue by tchapi** [hhvm/hack-hhvm-docs#534]
Hi,

I didn't find in the documentation why the `$stClassObject->{$var}` notation gives  an **Expected Expression** in strict mode (apart from the *Dynamic method call* problem); In the following example running on the 3.6.1 build, is there a reason why the type checker outputs such an error on the third try ? Is there any alternative to dynamically get the property of an object while still being in strict mode ?

```hack
<?hh // strict
class Stuff  {
  public function test(): void {
    $object = new stdClass();
    $object->a = "foobar";
    $a = 'a';
    $object[$a]; // 1. This is not an object of type KeyedContainer, this is an object of type stdClass
    $object->$a; // 2. Dynamic method call (Naming[2011])
    $object->{$a}; // 3. Expected expression (Parsing[1002]) + Dynamic method call (Naming[2011])
  }
}
```

Thanks a lot !
-- c

**Comment by paulbiss** [comment]
I don't think hack understands the `->{...}` syntax and the expected expression error is complaining about that.

**Comment by tchapi** [comment]
Thanks for your answer.
Even if it runs fine in HHVM, I understand the type checker doesn't like variable variables (as documented [here](http://docs.hhvm.com/manual/en/hack.unsupported.php) and in [this closed issue](https://github.com/hhvm/hack-hhvm-docs/issues/343)), but I guess the type checker should definitely not report a **Expected Expression**, and only a **Dynamic method call**; The `// UNSAFE` flag is not observed by the type checker either in this particular case, which I guess is not normal ?

It's not a real problem when writing a simple example code like the one above, but when there's unrelated code in the same file, somehow the type checker loses control and output hundreds of unrelated errors — it seems like it never recovers from this **Expected Expression** thing in some specific cases.

Maybe there's a better place to report this thing by the way ?

Thanks a lot

**Comment by paulbiss** [comment]
It's probably getting into a state where it doesn't really understand syntax and can't generate a perfect AST. I'm not sure what the best solution here is, @jwatzman may have some ideas.

**Comment by fredemmott** [comment]
The dynamic warning is strict mode, but the parsing error is not. Hack is not a full superset of PHP, and the typechecker's parser is a Hack parser; it is not expected to be able to parse arbitrary PHP syntax.

**Comment by fredemmott** [comment]
This specific case could be called out on http://docs.hhvm.com/manual/en/hack.unsupported.php - it is a dynamic feature though.

**Comment by tchapi** [comment]
Ok, that does make sense, thanks for your answer @fredemmott. I guess it could be added as an unsupported feature, just for clarity and newcomers that look into the docs to translate an existing PHP code base into Hack.

**Comment by jwatzman** [comment]
It's unsupported in strict, but shouldn't be a parse error. We can keep this open to update the docs as @fredemmott suggested to specifically call out variable-variable member access, but can you also open an issue against the HHVM project so we can fix the typechecker to generate a more useful error?

**Comment by tchapi** [comment]
Yes, I will. Thanks

**Comment by tchapi** [comment]
:+1:
