### ISSUE TITLE
Bug in hack.annotations.generators.php

### ISSUE THREAD

**Issue by Sander-Toonen** [hhvm/hack-hhvm-docs#536]
When running ```hh_client``` on the source code example of the generator function I get the following output:

````
./test.php:4:3,7: Invalid yield (Typing[4110])
./test.php:3:17,28: This is an object of type Continuation
  ./test.php:4:3,7: It is incompatible with an object of type Generator (result of function with 'yield' in the body)
````
However, using Generator as return type does not solve the problem. What is the correct way of typing a generator function?

Version info:
````
$ hh_client --version
ee54f360eac1f3dcb2fa6755931031d82c6e0ac9 Feb 19 2015 02:07:29
````

**Comment by SiebelsTim** [comment]
The return type for generators apparently got renamed in 56312033c5049c42a7b0eef446dba617fdd60c98. So typehinting `Generator` is the answer I suppose.

This should be fixed in the docs ASAP in my opinion :)

**Comment by jwatzman** [comment]
This is my fault, sorry about this. Thanks for reporting @Sander-Toonen and thanks for looking into it @SiebelsTim. Sounds like you're on the fix, as well?

Info in case it isn't clear from the hhi file. Suppose we have a generator that has a statement

`$r = yield $k => $v;`

Then the type of that generator is `Generator<Tk, Tv, Ts>`, where `Tk` is the type of `$k`, `Tv` is the type of `$v`, and `Ts` is the type of `$r`.

**Comment by Sander-Toonen** [comment]
Thank you @SiebelsTim and @jwatzman. I'm not sure I get why ```$r``` needs to be typed in your example but using ```\Generator<int, string, void>``` for a function yielding strings did the trick.

**Comment by SiebelsTim** [comment]
`$r` has the type of `Ts` because you set a variable equal to `yield`. So you want to `send()` something to the generator. You don't need it, when you simply use `yield "bla";` like you do in the example.

**Comment by Sander-Toonen** [comment]
Ah, I get it now. I was unfamiliar with the ```Generator::send()``` method. Thank you.

**Comment by SiebelsTim** [comment]
Closed in https://github.com/hhvm/hack-hhvm-docs/commit/29aec960377b75d7a4fd945decdf37a376dbd4cf
