### ISSUE TITLE
hackfuncref.php should describe Sets

### ISSUE THREAD

**Issue by fmoo** [hhvm/hack-hhvm-docs#539]
The `Sets` class does not appear to be documented anywhere, although it is referenced in http://docs.hhvm.com/manual/en/hack.collections.set.php

`Sets::intersect()` and the variety of other are very useful and could use documenting.

**Comment by JoelMarcey** [comment]
Actually, that's a bug. There is no `Sets` class; only `Set`. And `intersect` doesn't exist for a `Set`. I will fix this sentence.

You are looking for this.. http://docs.hhvm.com/manual/en/class.hack.settv.php

**Comment by fmoo** [comment]
Thanks Joel,

So to be clear, for determining the intersection, union, or difference of two sets (a fairly common operation for sets), there is no method provided by the standard hack collections library?

Should there be?

**Comment by JoelMarcey** [comment]
@fmoo We actually have some functions internally in a class called `Sets` that provides those helpers, like `intersect`. I do not see a reason why we can't make them public; I think they just never became public. They are all written in Hack, iirc. Let's see what we can do.

cc: @jwatzman

**Comment by fredemmott** [comment]
'Sets', 'Vectors', and 'Maps' contained APIs that either we did not consider useful to release (compatibility with legacy FB-internal array functions), or where we weren't sure that the API was actually right yet - and once it's in HHVM, it's much harder to change without harming users. These definitely shouldn't be dropped in verbatim - but we keep on talking about merging some of their functionality into Set, Vector, and Map.

**Comment by JoelMarcey** [comment]
The API reference will be more clear in our new docs...

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
