### ISSUE TITLE
Bug in install.hack.bootstrapping.php

### ISSUE THREAD

**Issue by ClaudiuC** [hhvm/hack-hhvm-docs#540]
Seems unclear - are .hhi files supported in the latest version or not?

![screen shot 2015-04-23 at 4 44 31 pm](https://cloud.githubusercontent.com/assets/821842/7309830/3acf4e18-e9d8-11e4-9fee-b7913e4ad6b2.png)

**Comment by fredemmott** [comment]
- including the 'standard' HHI files is no longer required or supported
- adding extra ones is still supported

Leaving issue open as the docs should be updated/clarified.

**Comment by JoelMarcey** [comment]
I have an HHI placeholder for the new docs.
