### ISSUE TITLE
Bug in hack.async.mysql.asyncmysqlconnectionpool.getpoolstats.php

### ISSUE THREAD

**Issue by tonyhhyip** [hhvm/hack-hhvm-docs#542]
The page should be AsyncMysqlConnectionPool::getPoolStats, but in the Description write about 'public function setPoolsConnectionLimit ( void ): array'

**Comment by JoelMarcey** [comment]
Thanks, this will be updated in our new docs.

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
