### ISSUE TITLE
Please document the hh_client options

### ISSUE THREAD

**Issue by tslettebo** [hhvm/hack-hhvm-docs#555]
The options to `hh_client` are partially documented through the  `--help` option. However, it's not necessarily obvious how to use them, so it would be good with a page documenting them.

For example, I've been trying to figure out how `--type-at-pos` can be used (assuming it's working), and the documentation says:

`--type-at-pos            (mode) show type at a given position in file [line:character]`

For one thing, it doesn't state what `mode` is, and for another, it doesn't state the precise order and format of its parameters.

I've tried e.g. `hh_client --type-at-pos <file> <line>:<character>`, and other variants, but nothing worked.

Could someone help with this one in particular?

**Comment by steelbrain** [comment]
```
steel@Black-Beauty:/var/www$ hh_client --type-at-pos "785:22" < main.hh
MySQL
```
That MySQL meant a MySQL class instance.

**Comment by tslettebo** [comment]
Thanks. :)

**Comment by JoelMarcey** [comment]
The new docs will have a whole section on `hh_client` options.

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo

**Comment by tslettebo** [comment]
That's great. :)
