### ISSUE TITLE
Bug in migrationhhvm.differences.php

### ISSUE THREAD

**Issue by photodude** [hhvm/hack-hhvm-docs#561]
Differences between PHP 5.5.x and HHVM is just a "Coming Soon" which is less than helpful. Please provide some guidance on how to migrate from PHP 5.x to HHVM [version? maybe 3.6.2?]

**Comment by paulbiss** [comment]
We have a document for intentional inconsistencies, but we should definitely update this with common issues, known bugs, etc. Thanks!

In the meantime this may be of some help: https://github.com/facebook/hhvm/blob/master/hphp/doc/inconsistencies

**Comment by JoelMarcey** [comment]
We are creating a whole documentation system with updated/new content. I have a placeholder for inconsistencies. 

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
