### ISSUE TITLE
Bug in class.hack.async.mysql.asyncmysqlconnectionpool.php

### ISSUE THREAD

**Issue by jamesgpearce** [hhvm/hack-hhvm-docs#562]
One part of doc says getPoolStats, another says setPoolsConnectionLimit for the same thing, and then in http://docs.hhvm.com/manual/en/hack.async.mysql.asyncmysqlconnectionpool.getpoolstats.php - very confused...

**Comment by JoelMarcey** [comment]
Less confusion is coming in the new docs (hopefully)!
