### ISSUE TITLE
Bug in function.hack.curl-multi-await.php

### ISSUE THREAD

**Issue by faaliyet** [hhvm/hack-hhvm-docs#570]
During lulls in network activity, the await curl_multi_async($mh); allows us to  .....

==>

During lulls in network activity, the await curl_multi_await($mh); allows us to 

Seems like this has been copied from http://hhvm.com/blog/7091/async-cooperative-multitasking-for-hack. so, this bug report also goes for that post .

**Comment by SiebelsTim** [comment]
cc @sgolemon for the blog post.

**Comment by JoelMarcey** [comment]
Thanks @SiebelsTim
