### ISSUE TITLE
"Constructor argument promotion" is actually parameter promotion

### ISSUE THREAD

**Issue by oyamauchi** [hhvm/hack-hhvm-docs#576]
http://docs.hhvm.com/manual/en/hack.constructorargumentpromotion.php

In the book, I decided to get all pedantic about the distinction between parameters and arguments (parameters are variables, and arguments are values), which led me to notice this. Shouldn't be much of a problem to rename it. (I'm going to refer to it as constructor parameter promotion in the book.)

**Comment by JoelMarcey** [comment]
The new docs will make this distinction. Thanks @oyamauchi. 

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
