### ISSUE TITLE
Bug in soapclient.soapclient.php

### ISSUE THREAD

**Issue by soundslocke** [hhvm/hack-hhvm-docs#577]
The heading at the top of the [soapclient.soapclient.php](http://docs.hhvm.com/manual/en/soapclient.soapclient.php) page says that it is not supported in HHVM, yet the [soap.installation.php](http://docs.hhvm.com/manual/en/soap.installation.php) page says that it is part of HHVM. Running a quick test to instantiate a `new SoapClient` in HHVM seemed to work... is there some aspect of SoapClient that is not functioning?

**Comment by SiebelsTim** [comment]
Mhpf, this is the result of it being an alias of `__construct`. Which is deprecated.
Additionally `method_exists("SoapClient", "SoapClient");` returns false on both, php and hhvm. 

I think we should just remove the duplicate and go with the `__construct` page.

**Comment by JoelMarcey** [comment]
Exactly what is supported and not supported will be more apparent in our new documentation: https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
