### ISSUE TITLE
hack.unsupported.php incomplete

### ISSUE THREAD

**Issue by apreiml** [hhvm/hack-hhvm-docs#583]
Hi,

I was reading the unsupported PHP features page and I didn't understand why references aren't allowed. A little explanation would be nice.

**Comment by JoelMarcey** [comment]
I have a placeholder section on this in our new docs that is being live developed; https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo

Basically references don't let the typechecker do static analysis in any reasonable way. It throws the whole typechecking paradigm out of whack.
