### ISSUE TITLE
Bug in function.mcrypt-create-iv.php

### ISSUE THREAD

**Issue by gessel** [hhvm/hack-hhvm-docs#587]
In certain environments, such as a jail on FreeBSD, the following fails (times out without returning a value):

 $iv = mcrypt_create_iv( $rem, MCRYPT_DEV_URANDOM );

The following reference states that the following variation "will first try to use MCRYPT_DEV_URANDOM, if it is not available, it will try to use MCRYPT_RAND"

  $iv = mcrypt_create_iv( $rem, MCRYPT_DEV_URANDOM|MCRYPT_RAND );

Indeed, this does not time out and works normally.  However, it would appear that "MCRYPT_RAND uses the non-cryptographically-secure rand() pesudo-random number generator " and the above construction may not work as the cited reference states, rather:

"No, that answer is completely wrong.

The mcrypt constants are:
MCRYPT_DEV_RANDOM = 0
MCRYPT_DEV_URANDOM = 1
MCRYPT_RAND = 2
 
Take a look at the source of mcrypt_create_iv.
https://github.com/php/php-src/blob/89b49b0/ext/mcrypt/mcrypt.c#L1339-L1382

MCRYPT_DEV_URANDOM|MCRYPT_RAND will result in 3.

3 is not equal to MCRYPT_DEV_RANDOM (0) or MCRYPT_DEV_URANDOM(1). So by using 3 php will always use the php_rand() pesudo-random generator with this code.

mcrypt_create_iv has no concept of fallbacks.

The issue here in the first place is that urandom is blocking (supposedly waiting for randomness from random?) and code is timing out waiting for it. Timeouts like that aren't trivial to detect and fallback (otherwise we would already have some in MWCryptRand). Even if it could then that would mean it would have to wait for a short timeout to happen each and every time before falling back."

The goal of producing portable code that would "fall back" to MCRYPT_RAND if, and only if, DEV_URANDOM isn't available would be a Very Good Thing.  Is this possible?

**Comment by JoelMarcey** [comment]
The documentation is from php.net. We are going to defer to this documentation in our new docs:

https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo

That said, you can file an issue in github.com/facebook/hhvm if you want some sort of behavior change.
