### ISSUE TITLE
Bug in intro.async.mysql.php

### ISSUE THREAD

**Issue by homerhsing** [hhvm/hack-hhvm-docs#588]
a typo:
  "AsynMysqlConnectionPool"  should be "AsyncMysqlConnectionPool"

the typo's position:

"There are 11 classes associated with async MySQL:

AsyncMysqlClient

AsynMysqlConnectionPool    <--  the typo is here  "

**Comment by JoelMarcey** [comment]
Thanks. This will be corrected in the new docs.
