### ISSUE TITLE
Bug in function.hack.class_meth.php

### ISSUE THREAD

**Issue by manzyuk** [hhvm/hack-hhvm-docs#590]
The documentation doesn't mention that `$method_name` cannot be the name of a private method even if `class_meth` is called from within the class in which that method is defined.  Example:

    <?hh // strict
    
    class C {
      private static function f(): void {
      }
      
      public function g(): void {
        $f = class_meth('C', 'f');
        $f();
      }
    }

I'm getting the following error:

    File "/home/manzyuk/scratch/class_meth.php", line 4, characters 27-27:
    This is a private method (Typing[4078])
    File "/home/manzyuk/scratch/class_meth.php", line 8, characters 10-29:
    you cannot use it with class_meth (whether you are in the same class or not).

**Comment by JoelMarcey** [comment]
I have this mentioned for the new docs. Thanks!
