### ISSUE TITLE
Bug in language.operators.assignment.php

### ISSUE THREAD

**Issue by stanri** [hhvm/hack-hhvm-docs#591]
Shouldn't you also mention -> and ?-> in here? I came looking for references to the ?-> operator, but can't find it anywhere, and I'm not entirely sure what it does (is it just saying the return of the method can be null?)

**Comment by SiebelsTim** [comment]
I don't think that page is the best fit as `->` and `?->` are *not* assignments. 

There is already #360 for the nullsafe operator.

**Comment by stanri** [comment]
Whoops you're right, don't know what I was thinking lol. Thanks!

**Comment by JoelMarcey** [comment]
The new docs we are building will have all the Hack operators documented and hopefully better searchability too.
