### ISSUE TITLE
Bug in datetime.formats.time.php

### ISSUE THREAD

**Issue by elav** [hhvm/hack-hhvm-docs#593]
Hi.. I created a new blog and mounted my VPS using Nginx + HHVM + MariaDB + Wordpress. The problem is that on the date of the comments I get something like this:

07 07UTC August 07UTC 2015 a las 11:59 11Fri, 07 Aug 2015 11:59:25 +000025. 

How I can fix it?

**Comment by paulbiss** [comment]
This doesn't sound like a documentation issue. Maybe try asking on Freenode in #hhvm or #hhvm-dev.
