### ISSUE TITLE
Bug in imagick.construct.php

### ISSUE THREAD

**Issue by MiyamuraMiyako** [hhvm/hack-hhvm-docs#594]
I use ```$imk = new Imagick( 'xxx.png' );```,but always caught this exception:```Caught exception: Unable to read image file```.I make sure picture is no problem. 
And in php5.6.12 & imagick3.1.2,not has this problem.

**Comment by AssemblyXiang** [comment]
This is my hhvm cmake command:
```shell
cmake \
-D LIBMAGICKWAND_INCLUDE_DIRS="/usr/local/ImageMagick-6.9.1-10/include/ImageMagick-6" \
-D LIBVPX_INCLUDE_DIRS="/usr/lib64" \
-D LIBMAGICKWAND_LIBRARIES="/usr/local/ImageMagick-6.9.1-10/lib/libMagickWand-6.Q16.so" \
-D LIBMAGICKCORE_LIBRARIES="/usr/local/ImageMagick-6.9.1-10/lib/libMagickCore-6.Q16.so" .
```

**Comment by JoelMarcey** [comment]
This should be an issue for the main HHVM repo, if it still exists.

https://github.com/facebook/hhvm
