### ISSUE TITLE
Bug in memcached.sessions.php

### ISSUE THREAD

**Issue by cosmok** [hhvm/hack-hhvm-docs#595]
It needs to be made clear that 
memcached.sess_prefiIx needs to be set in the ini file
something like:
```memcached.sess_prefiIx = "memc.sess.key." ```
otherwise was getting this error:
```Fatal error: Failed to initialize storage module: memcached....```
on
HipHop VM 3.8.0 (rel)

**Comment by JoelMarcey** [comment]
Can you verify this is necessary on HHVM 3.10? And if so, we can document it on the new docs. File an issue https://github.com/hhvm/user-documentation/issues

Thanks!
