### ISSUE TITLE
Bug in hack.lambda.php

### ISSUE THREAD

**Issue by orren** [hhvm/hack-hhvm-docs#596]
this page makes two references to capturing external variables with the use(..) keyword and provides no examples of how to do that.

**Comment by simonwelsh** [comment]
That's because those references are talking about PHP-style closures. Lambdas are auto-capturing, so there's no need for `use`.

**Comment by JoelMarcey** [comment]
@orren We are working on a new set of docs also; hopefully the use of lambdas will be made more clear there as well.
