### ISSUE TITLE
Bug in hack.asio.function.v.php

### ISSUE THREAD

**Issue by JesseXie** [hhvm/hack-hhvm-docs#599]
This code is not working:
Fatal error: Return type hint for async function getPages() must be awaitable

<?hh

async function getPages(...$urls): Vector<string> {
  $waitHandles = Vector {};
  foreach ($urls as $url) {
    $waitHandles[] = HH\asio\curl_exec($url);
  }
  return await HH\asio\v($waitHandles);
}

$pages = getPages($url0, $url1, $url2)->join();
echo $pages[0], $pages[1], $pages[2];

**Comment by fredemmott** [comment]
Yep, the return type needs to be `Awaitable<Vector<string>>`. This will be fixed (and automatically tested) in the updated docs site.

**Comment by JoelMarcey** [comment]
This should be fixed now in the new docs.
