### ISSUE TITLE
Bug in hack.async.fetchingexample.php : GenArrayWaitHandle is used, but never defined

### ISSUE THREAD

**Issue by deadalnix** [hhvm/hack-hhvm-docs#610]
Looking for GenArrayWaitHandle in the documentation yields no result. It is used in the example, but not documented, which makes the example confusing.

**Comment by JoelMarcey** [comment]
We are revamping the documentation for Hack and HHVM, and all of the examples will be updated to reflect reality. If you want to see what we are doing: 

https://github.com/hhvm/user-documentation
