### ISSUE TITLE
Creating an empty set - new Set() vs Set { }

### ISSUE THREAD

**Issue by Daniel15** [hhvm/hack-hhvm-docs#611]
The [docs for Set](http://docs.hhvm.com/manual/en/hack.settv.construct.php) say:

> Creates an empty Set (**if no parameters are passed**) or creates a Set from a Traversable. There are three primary ways to construct a Set:

> ```php
> $v = new Set(); // empty
> ```

However, `Set.hhi` says this:

```php
/**
 * Creates a Set from the given Traversable, or an empty Set
 * if "null" is passed.
 */
public function __construct(?Traversable<Tv> $it);
```

Which means that the first parameter is expected, and an error like this is thrown if you do `new Set()` as per the docs:

```
test.php:122:20,30: Too few arguments (Typing[4104])
  /tmp/hh_server/hhi_22cbc072/hhi/collections/Set.hhi:52:19,29: Definition is here
```

Which behaviour is the correct one? Is the documentation wrong, or is Set.hhi wrong? Should I be able to do `(new Set())` to get an empty set, or must I explicitly do `(new Set(null))`? 

Based on an internal group post, it looks like `new Set()` is no longer recommended and I should be doing `Set { }` instead, which can be chained like `(Set { })->addAll($foo)->addAll($bar)`. In this case, all references to `new Set()` in the docs should be changed to `Set { }`.

**Comment by SiebelsTim** [comment]
Yes, it's definitly the literal syntax that is recommended now. 
There were (apparently are) a couple of places where the docs used the old contructor and we tried to get rid of them.
This is going to be adressed in the docs revamp currently ongoing.
