### ISSUE TITLE
Code examples format issues on android 4.4 chrome

### ISSUE THREAD

**Issue by slinkp** [hhvm/hack-hhvm-docs#613]
![screenshot_2015-10-24-10-30-05](https://cloud.githubusercontent.com/assets/98610/10710964/c7e0f264-7a3a-11e5-8af6-d34360cd817f.png)

The line numbers appear above all the code, and code often goes beyond the margins to become invisible over the black background.

**Comment by JoelMarcey** [comment]
We are relaunching a redesign of the site that should address this issue. The plan is to have that come out in the next few weeks or so. 

We have a new repo for the updated docs.

https://github.com/hhvm/user-documentation
