### ISSUE TITLE
Bug in hack.mcrouter.mcrouter.decr.php

### ISSUE THREAD

**Issue by zekiunal** [hhvm/hack-hhvm-docs#615]
![bug](https://cloud.githubusercontent.com/assets/1094656/10772023/8d0bb72c-7cfc-11e5-9c7c-38edff842f3c.png)

**Comment by JoelMarcey** [comment]
Thanks! New docs coming soon where API definitions will be rendered directly from the HHVM source code.

https://github.com/hhvm/user-documentation
