### ISSUE TITLE
Bug in hack.shapes.php

### ISSUE THREAD

**Issue by Yostage** [hhvm/hack-hhvm-docs#616]
The syntax highlighting isn't working in the shape example. It looks like the string coloring is leaking out of the => and never closing. This is on Chrome, repros for me on Firefox as well.

![screenshot 2015-10-29 09 15 01](https://cloud.githubusercontent.com/assets/1382538/10824423/8d7ad266-7e1d-11e5-9d62-0e70a4d27586.png)

**Comment by JoelMarcey** [comment]
Our new docs site coming out soon should hopefully remedy this issue.

https://github.com/hhvm/user-documentation/
