### ISSUE TITLE
Confusing example code in hack.nullable.php

### ISSUE THREAD

**Issue by ryandm** [hhvm/hack-hhvm-docs#619]
The example code `check_not_null` is confusing to someone who's completely new to hack and trying to understand the deal with nullability. A careful reading of the docs and code makes it clear that the point of the example code is to demonstrate the meaning of `?int` as opposed to `int`, but the first impression is that explicit `check_not_null`-type logic is recommended as good hack style (as opposed to relying on hack's static analysis via the `?` operand).

A couple possible ideas for alternate example code:

1. "get with default" code that returns the second arg as the default value if the first arg is null
2. "pretty print the time" code that uses system time if the time arg is null

**Comment by JoelMarcey** [comment]
We are totally revamping the docs and most of the examples you see on the current site will be replaced.

Here is what we have for nullable....

https://github.com/hhvm/user-documentation/blob/master/guides/hack/01-types/02-type-system.md#nullable

You will notice @@ ... @@ that will be rendered into the example on the new site, but here is the raw example.

https://github.com/hhvm/user-documentation/blob/master/guides/hack/01-types/02-type-system-examples/nullable.php

A beta of the new site is planned really soon.

I am going to close this in favor of the new docs...

**Comment by ryandm** [comment]
Sounds good, thanks Joel.
