### ISSUE TITLE
RAM & CPU requirements?

### ISSUE THREAD

**Issue by RobLewis** [hhvm/hack-hhvm-docs#92]
I have searched in vain for any information about how much RAM and CPU are needed to run HHVM. For example, could it be run experimentally on an old PC (2.8 GHz P4 w/1.5GB RAM) running Ubuntu 12.0.4?

**Comment by JoelMarcey** [comment]
We usually recommend at least 2GB, but more is better. Will be clearer in the new docs. See https://github.com/hhvm/hack-hhvm-docs#update-and-direction-of-this-repo
